### ISSUE TITLE
[Suggestion] Add CodeGym to coding resources

### ISSUE THREAD

**Issue by sara-02** [jamooraa/jamooraa.github.io#1]
Link: https://codegym.cc/quests/tutorial/landing

**Comment by kishansagathiya** [comment]
@sara-02 This looks really good to me. Nice and fun way to learn programming. It reminds me of `Head First Java` (that's where I learnt Java from). Codegym is interactive as well. Definitely going to add it.

**Comment by kishansagathiya** [comment]
Added in `Other helpful important subjects`
